name: github pages

on:
  push:
    branches:
      - profile

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: '18.x'
            - name: Install pnpm
              run: npm install -g pnpm
            - name: Cache node modules
              uses: actions/cache@v2
              with:
                path: ~/.pnpm-store
                key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                  ${{ runner.os }}-pnpm-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            
            - name: Next build
              run: pnpm run build
            
            - name: Export
              run: pnpm run export && ls ./
            
            - name: Add nojekyll
              run: touch out/.nojekyll

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./out
